const events = require('../../../../app/constants/events')

test('events exports correct events', () => {
  expect(events.PAYMENT_EXTRACTED).toBe('uk.gov.defra.ffc.pay.payment.extracted')
  expect(events.PAYMENT_ENRICHED).toBe('uk.gov.defra.ffc.pay.payment.enriched')
  expect(events.PAYMENT_PAUSED_CROSS_BORDER).toBe('uk.gov.defra.ffc.pay.payment.paused.cross-border')
  expect(events.PAYMENT_PAUSED_DEBT).toBe('uk.gov.defra.ffc.pay.payment.paused.debt')
  expect(events.PAYMENT_DEBT_ATTACHED).toBe('uk.gov.defra.ffc.pay.payment.debt.attached')
  expect(events.PAYMENT_PAUSED_LEDGER).toBe('uk.gov.defra.ffc.pay.payment.paused.ledger')
  expect(events.PAYMENT_LEDGER_ASSIGNED).toBe('uk.gov.defra.ffc.pay.payment.ledger.assigned')
  expect(events.PAYMENT_PAUSED_QUALITY_CHECK).toBe('uk.gov.defra.ffc.pay.payment.ledger.quality-check.pending')
  expect(events.PAYMENT_QUALITY_CHECK_FAILED).toBe('uk.gov.defra.ffc.pay.payment.ledger.quality-check.failed')
  expect(events.PAYMENT_QUALITY_CHECK_PASSED).toBe('uk.gov.defra.ffc.pay.payment.ledger.quality-check.passed')
  expect(events.PAYMENT_RESET).toBe('uk.gov.defra.ffc.pay.payment.reset')
  expect(events.PAYMENT_PROCESSED).toBe('uk.gov.defra.ffc.pay.payment.processed')
  expect(events.PAYMENT_SUBMITTED).toBe('uk.gov.defra.ffc.pay.payment.submitted')
  expect(events.PAYMENT_ACKNOWLEDGED).toBe('uk.gov.defra.ffc.pay.payment.acknowledged')
  expect(events.PAYMENT_SETTLED).toBe('uk.gov.defra.ffc.pay.payment.settled')
  expect(events.PAYMENT_SUPPRESSED).toBe('uk.gov.defra.ffc.pay.payment.suppressed.recovery')
})
