const statuses = require('../../../../app/constants/statuses')

test('statuses exports correct statuses', () => {
  expect(statuses.PAYMENT_EXTRACTED_STATUS).toBe('Batch received')
  expect(statuses.PAYMENT_ENRICHED_STATUS).toBe('Request enriched with mandatory data')
  expect(statuses.PAYMENT_PAUSED_CROSS_BORDER_STATUS).toBe('Waiting for Cross Border calculation')
  expect(statuses.PAYMENT_PAUSED_DEBT_STATUS).toBe('Waiting for debt data')
  expect(statuses.PAYMENT_DEBT_ATTACHED_STATUS).toBe('Debt data attached')
  expect(statuses.PAYMENT_PAUSED_LEDGER_STATUS).toBe('Waiting for ledger assignment')
  expect(statuses.PAYMENT_LEDGER_ASSIGNED_STATUS).toBe('Ledger assigned')
  expect(statuses.PAYMENT_PAUSED_QUALITY_CHECK_STATUS).toBe('Waiting for ledger assignment quality check')
  expect(statuses.PAYMENT_QUALITY_CHECK_FAILED_STATUS).toBe('Ledger assignment quality check failed, waiting for correction')
  expect(statuses.PAYMENT_QUALITY_CHECK_PASSED_STATUS).toBe('Ledger assignment quality check passed')
  expect(statuses.PAYMENT_RESET_STATUS).toBe('Reset to be recalculated')
  expect(statuses.PAYMENT_PROCESSED_STATUS).toBe('Calculation of final state completed')
  expect(statuses.PAYMENT_SUBMITTED_STATUS).toBe('Submitted to payment ledger')
  expect(statuses.PAYMENT_ACKNOWLEDGED_STATUS).toBe('Acknowledged by payment ledger')
  expect(statuses.PAYMENT_SETTLED_STATUS).toBe('Settled by payment ledger')
  expect(statuses.PAYMENT_SUPPRESSED_STATUS).toBe('Accounts Receivable value suppressed due to closure')
})
