services:
  ffc-pay-tracking:
    build:
      context: .
      target: production
    image: ffc-pay-tracking
    container_name: ffc-pay-tracking
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-tracking-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
