version: '3.8'

services:
  ffc-pay-tracking:
    build:
      context: .
      target: production
    image: ffc-pay-tracking
    container_name: ffc-pay-tracking
    depends_on:
      - ffc-pay-tracking-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-tracking-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      REQUEST_RESPONSE_TOPIC_ADDRESS: ${REQUEST_RESPONSE_TOPIC_ADDRESS:-ffc-pay-request-response}${MESSAGE_QUEUE_SUFFIX}
      REQUEST_RESPONSE_SUBSCRIPTION_ADDRESS: ${REQUEST_RESPONSE_SUBSCRIPTION_ADDRESS:-ffc-pay-tracking}${MESSAGE_QUEUE_SUFFIX}
      PROCESSING_TOPIC_ADDRESS: ${PROCESSING_TOPIC_ADDRESS:-ffc-pay-processing}${MESSAGE_QUEUE_SUFFIX}
      PROCESSING_SUBSCRIPTION_ADDRESS: ${PROCESSING_SUBSCRIPTION_ADDRESS:-ffc-pay-tracking}${MESSAGE_QUEUE_SUFFIX}
      SUBMIT_TOPIC_ADDRESS: ${SUBMIT_TOPIC_ADDRESS:-ffc-pay-submit}${MESSAGE_QUEUE_SUFFIX}
      SUBMIT_SUBSCRIPTION_ADDRESS: ${SUBMIT_SUBSCRIPTION_ADDRESS:-ffc-pay-tracking}${MESSAGE_QUEUE_SUFFIX}
      RETURN_TOPIC_ADDRESS: ${RETURN_TOPIC_ADDRESS:-ffc-pay-return}${MESSAGE_QUEUE_SUFFIX}
      RETURN_SUBSCRIPTION_ADDRESS: ${RETURN_SUBSCRIPTION_ADDRESS:-ffc-pay-tracking}${MESSAGE_QUEUE_SUFFIX}
      ACKNOWLEDGEMENT_TOPIC_ADDRESS: ${ACKNOWLEDGEMENT_TOPIC_ADDRESS:-ffc-pay-acknowledgement}${MESSAGE_QUEUE_SUFFIX}
      ACKNOWLEDGEMENT_SUBSCRIPTION_ADDRESS: ${ACKNOWLEDGEMENT_SUBSCRIPTION_ADDRESS:-ffc-pay-tracking}${MESSAGE_QUEUE_SUFFIX}
      POSTGRES_DB: ffc_pay_tracking
      POSTGRES_HOST: ${POSTGRES_HOST:-ffc-pay-tracking-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
  
  ffc-pay-tracking-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_pay_tracking
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
