version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-pay-tracking:
    build:
      target: development
    image: ffc-pay-tracking-development
    container_name: ffc-pay-tracking-development
    ports:
      - "9299:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json

  ffc-pay-tracking-postgres:
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
