version: '3.8'

services:
  ffc-pay-tracking:
    build:
      context: .
      target: production
    image: ffc-pay-tracking
    container_name: ffc-pay-tracking
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-tracking-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      REQUEST_RESPONSE_TOPIC_ADDRESS: ${REQUEST_RESPONSE_TOPIC_ADDRESS:-ffc-pay-request-response}${MESSAGE_QUEUE_SUFFIX}
      REQUEST_RESPONSE_SUBSCRIPTION_ADDRESS: ${REQUEST_RESPONSE_SUBSCRIPTION_ADDRESS:-ffc-pay-tracking}${MESSAGE_QUEUE_SUFFIX}
      PROCESSING_TOPIC_ADDRESS: ${PROCESSING_TOPIC_ADDRESS:-ffc-pay-processing}${MESSAGE_QUEUE_SUFFIX}
      PROCESSING_SUBSCRIPTION_ADDRESS: ${PROCESSING_SUBSCRIPTION_ADDRESS:-ffc-pay-tracking}${MESSAGE_QUEUE_SUFFIX}
      SUBMIT_TOPIC_ADDRESS: ${SUBMIT_TOPIC_ADDRESS:-ffc-pay-submit}${MESSAGE_QUEUE_SUFFIX}
      SUBMIT_SUBSCRIPTION_ADDRESS: ${SUBMIT_SUBSCRIPTION_ADDRESS:-ffc-pay-tracking}${MESSAGE_QUEUE_SUFFIX}
      RETURN_TOPIC_ADDRESS: ${RETURN_TOPIC_ADDRESS:-ffc-pay-return}${MESSAGE_QUEUE_SUFFIX}
      RETURN_SUBSCRIPTION_ADDRESS: ${RETURN_SUBSCRIPTION_ADDRESS:-ffc-pay-tracking}${MESSAGE_QUEUE_SUFFIX}
      ACKNOWLEDGEMENT_TOPIC_ADDRESS: ${ACKNOWLEDGEMENT_TOPIC_ADDRESS:-ffc-pay-acknowledgement}${MESSAGE_QUEUE_SUFFIX}
      ACKNOWLEDGEMENT_SUBSCRIPTION_ADDRESS: ${ACKNOWLEDGEMENT_SUBSCRIPTION_ADDRESS:-ffc-pay-tracking}${MESSAGE_QUEUE_SUFFIX}
