services:
  ffc-pay-tracking:
    build:
      context: .
      target: production
    image: ffc-pay-tracking
    container_name: ffc-pay-tracking
    depends_on:
      - ffc-pay-tracking-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-tracking-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      EVENTS_TOPIC_ADDRESS: ${EVENTS_TOPIC_ADDRESS:-ffc-pay-events}${MESSAGE_QUEUE_SUFFIX}
      EVENTS_SUBSCRIPTION_ADDRESS: ${EVENTS_SUBSCRIPTION_ADDRESS:-ffc-pay-tracking}${MESSAGE_QUEUE_SUFFIX}
      POSTGRES_DB: ffc_pay_tracking
      POSTGRES_HOST: ${POSTGRES_HOST:-ffc-pay-tracking-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
      PAYMENTS_SERVICE_ENDPOINT: http://ffc-pay-processing:3008
      PROCESSING_ACTIVE: ${PROCESSING_ACTIVE:-true}

  ffc-pay-tracking-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_pay_tracking
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
