environment: production
environmentCode:
name: ffc-pay-tracking
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-tracking

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-pay-tracking-config-map

containerSecret:
  name: ffc-pay-tracking-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 150Mi
  limitCpu: 150m
  messageQueueHost: namespace.servicebus.windows.net
  requestResponseTopicAddress: ffc-pay-request-response
  requestResponseSubscriptionAddress: ffc-pay-tracking
  processingTopicAddress: ffc-pay-processing
  processingSubscriptionAddress: ffc-pay-tracking
  submitTopicAddress: ffc-pay-submit
  submitSubscriptionAddress: ffc-pay-tracking
  returnTopicAddress: ffc-pay-return
  returnSubscriptionAddress: ffc-pay-tracking
  acknowledgementTopicAddress: ffc-pay-acknowledgement
  acknowledgementSubscriptionAddress: ffc-pay-tracking

postgresService:
  postgresDb: ffc_pay_tracking
  postgresqlHost: ffc-pay-tracking-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
