environment: production
environmentCode:
name: ffc-pay-tracking
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-tracking

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-pay-tracking-config-map

containerSecret:
  name: ffc-pay-tracking-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 800Mi
  requestCpu: 800m
  port: 3002
  messageQueueHost: namespace.servicebus.windows.net
  eventsTopicAddress: ffc-pay-events
  eventsSubscriptionAddress: ffc-pay-tracking
  paymentsEndpoint: http://ffc-pay-processing.ffc-pay
  legacyProcessingActive: false

postgresService:
  postgresDb: ffc_pay_tracking
  postgresqlHost: ffc-pay-tracking-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

livenessProbe:
  path: /healthz
  port: 3002
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3002
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
