{{- include "ffc-helm-library.container-config-map" (list . "ffc-pay-tracking.config-map") -}}
{{- define "ffc-pay-tracking.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  PROCESSING_ACTIVE: {{ quote .Values.container.processingActive }}
  {{- if and (.Values.environmentCode) (not .Values.pr) }}
  EVENTS_TOPIC_ADDRESS: {{ .Values.container.eventsTopicAddress }}-{{ .Values.environmentCode }}
  {{ else }}
  EVENTS_TOPIC_ADDRESS: {{ .Values.container.eventsTopicAddress }}
  {{- end }}
  EVENTS_SUBSCRIPTION_ADDRESS: {{ quote .Values.container.eventsSubscriptionAddress }}
  POSTGRES_DB: {{ quote .Values.postgresService.postgresDb }}
  POSTGRES_HOST: {{ quote .Values.postgresService.postgresqlHost }}
  POSTGRES_PORT: {{ quote .Values.postgresService.postgresPort }}
  POSTGRES_SCHEMA_NAME: {{ quote .Values.postgresService.postgresSchema }}
  {{- if and (.Values.environmentCode) (not .Values.pr) }}
    {{- if ne .Values.environmentCode "snd" }}
  PAYMENTS_SERVICE_ENDPOINT: {{ .Values.container.paymentsEndpoint }}-{{ .Values.environmentCode }}
    {{ else }}
  PAYMENTS_SERVICE_ENDPOINT: {{ quote .Values.container.paymentsEndpoint }}
    {{- end }}
  {{ else }}
  PAYMENTS_SERVICE_ENDPOINT: {{ quote .Values.container.paymentsEndpoint }}
  {{- end }}

{{- end -}}
