module.exports = {
  PAYMENT_EXTRACTED_STATUS: 'Batch received',
  PAYMENT_ENRICHED_STATUS: 'Request enriched with mandatory data',
  PAYMENT_PAUSED_CROSS_BORDER_STATUS: 'Waiting for Cross Border calculation',
  PAYMENT_PAUSED_DEBT_STATUS: 'Waiting for debt data',
  PAYMENT_DEBT_ATTACHED_STATUS: 'Debt data attached',
  PAYMENT_PAUSED_LEDGER_STATUS: 'Waiting for ledger assignment',
  PAYMENT_LEDGER_ASSIGNED_STATUS: 'Ledger assigned',
  PAYMENT_PAUSED_QUALITY_CHECK_STATUS: 'Waiting for ledger assignment quality check',
  PAYMENT_QUALITY_CHECK_FAILED_STATUS: 'Ledger assignment quality check failed, waiting for correction',
  PAYMENT_QUALITY_CHECK_PASSED_STATUS: 'Ledger assignment quality check passed',
  PAYMENT_RESET_STATUS: 'Reset to be recalculated',
  PAYMENT_PROCESSED_STATUS: 'Calculation of final state completed',
  PAYMENT_SUBMITTED_STATUS: 'Submitted to payment ledger',
  PAYMENT_ACKNOWLEDGED_STATUS: 'Acknowledged by payment ledger',
  PAYMENT_SETTLED_STATUS: 'Settled by payment ledger',
  PAYMENT_SUPPRESSED_STATUS: 'Accounts Receivable value suppressed due to closure',
  BATCH_REJECTED_STATUS: 'Batch rejected by Payment Hub',
  BATCH_QUARANTINED_STATUS: 'Batch quarantined by Payment Hub',
  PAYMENT_REJECTED_STATUS: 'Payment rejected by Payment Hub',
  PAYMENT_DAX_REJECTED_STATUS: 'Payment rejected by D365',
  PAYMENT_INVALID_BANK_STATUS: 'Bank details missing in D365',
  PAYMENT_PROCESSING_FAILED_STATUS: 'Payment failed processing in Payment Hub',
  PAYMENT_SETTLEMENT_UNMATCHED_STATUS: 'Settlement data could not be matched to an existing payment',
  RESPONSE_REJECTED_STATUS: 'D365 response rejected by Payment Hub',
  PAYMENT_REQUEST_BLOCKED_STATUS: 'Debt information missing in Payment Hub',
  PAYMENT_DAX_UNAVAILABLE_STATUS: 'Payment Hub could not reach D365',
  RECEIVER_CONNECTION_FAILED_STATUS: 'Payment Hub could not establish connection to D365'
}
